model_params:
  objective: fair
  verbose: 0
  force_col_wise: True
  learning_rate: 0.08
  boosting_type: dart
  num_leaves: 11
  seed: 8

f_cols:
  - text_bigram_overlap
  - text_unique_bigrams
  - text_bigram_exclusive
  - text_bigram_ratio
  - text_bigram_diff
  - unique_ratio
  - n_words
  - unique_words
  - word_len_avg
  - word_len_q10
  - word_len_q90
  - verb_count
  - noun_count
  - adv_count
  - adj_count
  - det_count
