model_params:
  objective: fair
  verbose: 0
  force_col_wise: True
  learning_rate: 0.08
  boosting_type: dart
  num_leaves: 11
  seed: 42

f_cols:
  - text_bigram_overlap
  - text_unique_bigrams
  - unique_ratio
  - n_words
  - unique_words
  - word_len_avg
  - word_len_q10
  - word_len_q90
